# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Python Install-Test and Docker CI/CD

on:
  push:
    branches: [ master, '**' ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    working-directory: ./src
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Python install and test Python3 ${{ matrix.node-version }}
      uses: actions/setup-python@v2
      with:
        node-version: ${{ matrix.python-version }}
    - run: pip install -r requirements.txt
    - run: python3 manage.py test

  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: room-slot-booking # Provide only Docker image name, tag will be automatically set to latest
          dockerfile: Dockerfile